".build":
  variables:
    DOCKERFILE: $NAME_DOCKERFILE
    IMAGE_DOCKERFILE: >
      --dockerfile $CI_PROJECT_DIR/$DOCKERFILE
    TAG: "$CI_COMMIT_TAG"
    IMAGE_TAGS: >
      --destination $REGISTRY_URL/$CI_PROJECT_NAME:$TAG
    IMAGE_CONTEXT: >
      --context $CI_PROJECT_DIR
    IMAGE_ARGS: ''
    IMAGE_LABELS: >
      --label org.opencontainers.image.vendor=$CI_SERVER_URL/$GITLAB_USER_LOGIN
      --label org.opencontainers.image.authors=$CI_SERVER_URL/$GITLAB_USER_LOGIN
      --label org.opencontainers.image.revision=$CI_COMMIT_SHA
      --label org.opencontainers.image.source=$CI_PROJECT_URL
      --label org.opencontainers.image.documentation=$CI_PROJECT_URL
      --label org.opencontainers.image.licenses=$CI_PROJECT_URL
      --label org.opencontainers.image.url=$CI_PROJECT_URL
  image:
    name: "gcr.io/kaniko-project/executor:v1.23.2-debug"
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"${REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${REGISTRY_USER}" "${REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      $IMAGE_CONTEXT
      $IMAGE_DOCKERFILE
      $IMAGE_ARGS
      $IMAGE_TAGS
      $IMAGE_LABELS
