include:
  - local: 'functions.gitlab-ci.yml'

# -
flawfinder:
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/python:3.11.6-p9
  variables:
    SEARCH_MAX_DEPTH: 4
  extends:
    - ".sast_base"
    - ".artifacts"
  script:
    - find . -type f -name "*.c"
    - find . -type f -name "*.cc"
    - find . -type f -name "*.cpp"
    - find . -type f -name "*.c++"
    - find . -type f -name "*.cp"
    - find . -type f -name "*.cxx"
    - echo flawfinder
    - echo flawfinder > reports/flawfinder.json
  rules:
    - if: "$SAST_EXCLUDED_ANALYZERS =~ /flawfinder/"
      when: never
    - if: "$CI_COMMIT_BRANCH"
      exists:
        - "**/*.c"
        - "**/*.cc"
        - "**/*.cpp"
        - "**/*.c++"
        - "**/*.cp"
        - "**/*.cxx"
