include:
  - local: 'functions.gitlab-ci.yml'

# -
flawfinder:
  variables:
    SAST_IMAGE: $CI_REGISTRY/devops/python:3.11.6-p9
    SEARCH_MAX_DEPTH: 4
  extends:
    - ".sast_base"
  before_script:
    - mkdir reports/ || true
  script:
    - find . -type f -name "*.c"
    - find . -type f -name "*.cc"
    - find . -type f -name "*.cpp"
    - find . -type f -name "*.c++"
    - find . -type f -name "*.cp"
    - find . -type f -name "*.cxx"
    - echo flawfinder
    - echo flawfinder > reports/flawfinder.json
  rules:
    - if: "$SAST_DISABLED == 'true' || $SAST_DISABLED == '1'"
      when: never
    - if: "$SAST_EXCLUDED_ANALYZERS =~ /flawfinder/"
      when: never
    - if: "$CI_COMMIT_BRANCH"
      exists:
        - "**/*.c"
        - "**/*.cc"
        - "**/*.cpp"
        - "**/*.c++"
        - "**/*.cp"
        - "**/*.cxx"
  when: manual
  allow_failure: true
