include:
  - local: 'functions.gitlab-ci.yml'

# -
kubesec:
  variables:
    SAST_IMAGE: registry.gitlab.com/dc20e6/devsecops/images/python:3.11.6-p9
    SEARCH_MAX_DEPTH: 4
  extends:
    - ".sast_base"
    - ".artifacts"
  script:
    - echo kubesec
    - echo kubesec > reports/kubesec.json
  rules:
    - if: "$SAST_DISABLED == 'true' || $SAST_DISABLED == '1'"
      when: never
    - if: "$SAST_EXCLUDED_ANALYZERS =~ /kubesec/"
      when: never
    - if: "$CI_COMMIT_BRANCH && $SCAN_KUBERNETES_MANIFESTS == 'true'"
  when: manual
  allow_failure: true
