include:
  - local: 'functions.gitlab-ci.yml'

# -
nodejs-scan:
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/python:3.11.6-p9
  variables:
    SEARCH_MAX_DEPTH: 4
  extends:
    - ".sast_base"
    - ".artifacts"
  script:
    - find . -type f -name package.json
    - echo nodejs-scan
    - echo nodejs-scan > reports/nodejs-scan.json
  rules:
    - if: "$SAST_EXCLUDED_ANALYZERS =~ /nodejs-scan/"
      when: never
    - if: "$CI_COMMIT_BRANCH"
      exists:
        - "**/package.json"
