include:
  - local: 'functions.gitlab-ci.yml'

# -
nodejs-scan:
  variables:
    SAST_IMAGE: registry.gitlab.com/dc20e6/devsecops/images/python:3.11.6-p9
    SEARCH_MAX_DEPTH: 4
  extends:
    - ".sast_base"
  before_script:
    - mkdir reports/ || true
  script:
    - find . -type f -name package.json
    - echo nodejs-scan
    - echo nodejs-scan > reports/nodejs-scan.json
  rules:
    - if: "$SAST_DISABLED == 'true' || $SAST_DISABLED == '1'"
      when: never
    - if: "$SAST_EXCLUDED_ANALYZERS =~ /nodejs-scan/"
      when: never
    - if: "$CI_COMMIT_BRANCH"
      exists:
        - "**/package.json"
  when: manual
  allow_failure: true
