include:
  - local: 'functions.gitlab-ci.yml'

# -
salus:
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/python:3.11.6-p9
  variables:
    SEARCH_MAX_DEPTH: 4
  extends:
    - ".sast_base"
    - ".artifacts"
  script:
    - find . -type f -name "*.ipa"
    - find . -type d -name "*.xcodeproj"
    - echo salus
    - echo salus > reports/salus.json
  rules:
    - if: "$SAST_EXCLUDED_ANALYZERS =~ /salus/"
      when: never
    - if: "$CI_COMMIT_BRANCH"
      exists:
        - "**/*.rb"
        - "**/Gemfile"
        - "**/*.js"
        - "**/*.json"
        - "**/*.py"
        - "**/*.mjs"
        - "**/*.go"
        - "**/*.rs"
        - "**/*.toml"
        - "**/*.cargo"
