include:
  - local: 'functions.gitlab-ci.yml'

# -
sobelow:
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/python:3.11.6-p9
  variables:
    SEARCH_MAX_DEPTH: 4
  extends:
    - ".sast_base"
    - ".artifacts"
  script:
    - find . -type f -name "mix.exs"
    - echo sobelow
    - echo sobelow > reports/sobelow.json
  rules:
    - if: "$SAST_EXCLUDED_ANALYZERS =~ /sobelow/"
      when: never
    - if: "$CI_COMMIT_BRANCH"
      exists:
        - "**/mix.exs"
