include:
  - local: 'functions.gitlab-ci.yml'

# progpilot (https://github.com/designsecurity/progpilot)
progpilot:
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/progpilot:latest
  variables:
    SEARCH_MAX_DEPTH: 4
  extends:
    - ".sast_base"
  script:
    - progpilot . > reports/sast.progpilot.report.json
  after_script:
    - |
      if [ "$GENERATE_REPORT" = 'true' ]; then
        echo "Uploading"
        cat reports/sast.progpilot.report.json
      fi
  rules:
    - if: "$SAST_EXCLUDED_ANALYZERS =~ /progpilot/"
      when: never
    - if: "$SAST_DISABLED == 'true' || $SAST_DISABLED == '1'"
      when: never
    # - if: "$CI_COMMIT_BRANCH && $CI_PROJECT_REPOSITORY_LANGUAGES =~ /php/"
    - if: $CI_COMMIT_REF_NAME == $SECURITY_BRANCH
  when: manual
  allow_failure: true