include:
  - local: 'functions.gitlab-ci.yml'

psalm:
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/psalm:latest
  variables:
    PROJECT_DIR: /builds/$CI_PROJECT_PATH
  extends:
    - ".sast_base"
  script:
    - psalm .
  after_script:
    - echo "Uploading"
    - cat reports/sast.psalm.report.json
  rules:
    - if: "$SAST_EXCLUDED_ANALYZERS =~ /psalm/"
      when: never
    # - if: "$CI_COMMIT_BRANCH && $CI_PROJECT_REPOSITORY_LANGUAGES =~ /php/"
    - !reference [.sast_rule, rules]