variables:

  IMAGE_TO_SCAN: $APP_IMAGE:latest
  SECURITY_BRANCH: $CI_DEFAULT_BRANCH

stages:
  - .pre
  - Secrets
  - Lint
  - Audit (src)
  - SAST (src)
  - Build
  - Audit (image)
  - Deploy
  - DAST
  - .post

".artifacts":
  before_script:
    - mkdir reports/ || true
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - reports/
    expire_in: 1 day
    when: always

".secrets_base":
  stage: Secrets
  extends:
    - ".artifacts"

".lint_base":
  stage: Lint
  extends:
    - ".artifacts"

".audit_src_base":
  stage: Audit (src)
  extends:
    - ".artifacts"

".sast_base":
  stage: SAST (src)
  extends:
    - ".artifacts"

".audit_image_base":
  stage: Audit (image)
  extends:
    - ".artifacts"

".dast_base":
  stage: DAST
  extends:
    - ".artifacts"

# ".security_rule":
#   rules:
#     - if: $CI_COMMIT_REF_NAME == $SECURITY_BRANCH

".secrets_rule":
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_REF_NAME == $SECURITY_BRANCH
      variables:
        GENERATE_REPORT: "true"
        GENERATE_REPORT: "true"

".lint_rule":
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_REF_NAME == $SECURITY_BRANCH
      variables:
        GENERATE_REPORT: "true"
        GENERATE_REPORT: "true"

".audit_rule":
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        GENERATE_REPORT: "false"
    - if: $CI_COMMIT_REF_NAME == $SECURITY_BRANCH
      variables:
        GENERATE_REPORT: "true"

".audit_rule_mr":
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

".sast_rule":
  rules:
    - if: "$SAST_DISABLED == 'true' || $SAST_DISABLED == '1'"
      when: never
    - if: $CI_COMMIT_REF_NAME == $SECURITY_BRANCH
      variables:
        GENERATE_REPORT: "true"

".dast_rule":
  rules:
    - if: "$DAST_DISABLED == 'true' || $DAST_DISABLED == '1'"
      when: never
    - if: $CI_COMMIT_REF_NAME == $SECURITY_BRANCH
      variables:
        GENERATE_REPORT: "true"
