include:
  - local: '05-dast/k8s.cluster/kube-bench.gitlab-ci.yml'
  - local: '05-dast/k8s.cluster/kube-hunter.gitlab-ci.yml'
  - local: '05-dast/k8s.cluster/kubeaudit.gitlab-ci.yml'
  - local: '05-dast/k8s.cluster/kubescape.gitlab-ci.yml'
  - local: '05-dast/k8s.cluster/popeye.gitlab-ci.yml'
  - local: '05-dast/k8s.cluster/prowler.gitlab-ci.yml'
