include:
  - local: '05-dast/web/dastardly.gitlab-ci.yml'
  - local: '05-dast/web/nikto.gitlab-ci.yml'
  - local: '05-dast/web/nuclei.gitlab-ci.yml'
  - local: '05-dast/web/wapiti.gitlab-ci.yml'
  - local: '05-dast/web/zap.gitlab-ci.yml'
