include:
  - local: 'functions.gitlab-ci.yml'

# ESLint (https://eslint.org/)
eslint (sast):
  image:
    name: node:18-alpine
  variables:
    SEARCH_MAX_DEPTH: 4
  extends:
    - ".sast_base"
  before_script:
    - echo "Здесь необходимо переопределить блок before_script в соответствии с окружением"
  script:
    - echo "Здесь необходимо переопределить блок script в соответствии с окружением"
    - echo eslint > reports/sast.eslint.yarn.report.json
  after_script:
    - |
      if [ "$GENERATE_REPORT" = 'true' ]; then
        echo "Uploading"
        cat reports/sast.eslint.yarn.report.json
      fi
  rules:
    - if: "$SAST_EXCLUDED_ANALYZERS =~ /eslint/"
      when: never
    # - if: "$CI_COMMIT_BRANCH && $CI_PROJECT_REPOSITORY_LANGUAGES =~ /(javascript|typescript|jsx|tsx)/"
    - !reference [.sast_rule, rules]
