include:
  - local: 'functions.gitlab-ci.yml'

variables:
  DD_UPLOAD_REPORT: "true"

# Brakeman Scan (https://github.com/presidentbeef/brakeman)
Brakeman:
  variables:
    SAST_IMAGE: presidentbeef/brakeman
    SEARCH_MAX_DEPTH: 4
  extends:
    - ".sast_base"
  script:
    - /usr/src/app/bin/brakeman
      -f json
      -o reports/sast.brakeman.report.json
  after_script:
    - |
      if [ "$DD_UPLOAD_REPORT" = 'true' ]; then
        echo "Uploading"
        cat reports/sast.brakeman.report.json
      fi
  rules:
    - if: "$SAST_EXCLUDED_ANALYZERS =~ /brakeman/"
      when: never
    - if: "$SAST_DISABLED == 'true' || $SAST_DISABLED == '1'"
      when: never
    # - if: "$CI_COMMIT_BRANCH && $CI_PROJECT_REPOSITORY_LANGUAGES =~ /ruby/"
    - if: $CI_COMMIT_REF_NAME == $SECURITY_BRANCH
  when: manual
  allow_failure: true