include:
  - local: 'functions.gitlab-ci.yml'

# Semgrep https://github.com/semgrep/semgrep
Semgrep:
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/semgrep:latest
  variables:
    SEARCH_MAX_DEPTH: 4
    SEMGREP_CONFIG: "--config auto"
  extends:
    - ".sast_base"
  script:
    - |
      if [ "$GENERATE_REPORT" = 'true' ]; then
        semgrep scan $SEMGREP_CONFIG --json --json-output=reports/sast.semgrep.report.json --error
      else
        semgrep scan $SEMGREP_CONFIG
      fi
  after_script:
    - |
      if [ "$GENERATE_REPORT" = 'true' ]; then
        echo "Uploading"
        cat reports/sast.semgrep.report.json
      fi
  rules:
    - if: "$SAST_EXCLUDED_ANALYZERS =~ /semgrep/"
      when: never
    - !reference [.sast_rule, rules]
