include:
  - local: 'functions.gitlab-ci.yml'

variables:
  DD_UPLOAD_REPORT: "true"

# chart-testing
chart-testing:
  extends:
    - ".sast_base"
    - ".DefectDojo_variables"
  variables:
    IAC_IMAGE: quay.io/helmpack/chart-testing:v3.11.0
  script:
    - ct install
      --chart-dirs . 
      --charts .
  rules:
    - if: "$CI_COMMIT_BRANCH"
      exists:
        - "Chart.yaml"
        - "Chart.lock"
  when: manual

DefectDojo Engagement Creation:
  extends:
    - ".DefectDojo_Engagement_Creation"
