include:
  - local: 'functions.gitlab-ci.yml'

# chechov (https://github.com/bridgecrewio/checkov)
checkov:
  extends:
    - ".sast_base"
  variables:
    IAC_IMAGE: registry.gitlab.com/dc20e6/devsecops/images/checkov:3.2.91
  script:
    - checkov
      --framework helm
      -d .
      -o cli
      # -o json
      # --output-file-path reports/
  rules:
    - if: "$CI_COMMIT_BRANCH"
      exists:
        - "Chart.yaml"
        - "Chart.lock"
