include:
  - local: 'functions.gitlab-ci.yml'

variables:
  DD_UPLOAD_REPORT: "true"

# chechov (https://github.com/bridgecrewio/checkov)
checkov:
  extends:
    - ".sast_base"
    - ".DefectDojo_variables"
  variables:
    IAC_IMAGE: $CI_REGISTRY/devops/checkov:3.2.91
  script:
    - checkov
      --framework helm
      -d .
      -o cli
      # -o json
      # --output-file-path reports/
  rules:
    - if: "$CI_COMMIT_BRANCH"
      exists:
        - "Chart.yaml"
        - "Chart.lock"
  when: manual

DefectDojo Engagement Creation:
  extends:
    - ".DefectDojo_Engagement_Creation"
