include:
  - local: 'functions.gitlab-ci.yml'

# kubeconform (https://github.com/yannh/kubeconform)
kubeconform:
  extends:
    - ".sast_base"
  variables:
    IAC_IMAGE: registry.gitlab.com/dc20e6/devsecops/images/deploy-tools:latest
    HELM_VALUES_FILES: >
      -f values.yaml
  script:
    - helm plugin install https://github.com/jtyr/kubeconform-helm
    - helm kubeconform
      --verbose
      --summary
      $HELM_VALUES_FILES
      .
  when: manual