include:
  - local: 'functions.gitlab-ci.yml'

variables:
  DD_UPLOAD_REPORT: "true"

# kube-score (https://github.com/zegl/kube-score)
kube-score:
  extends:
    - ".sast_base"
    - ".DefectDojo_variables"
  variables:
    IAC_IMAGE: zegl/kube-score:v1.18.0
    HELM_VALUES_FILES: >
      -f values.yaml
  script:
    - helm template $HELM_VALUES_FILES . | kube-score score -
      --output-format sarif
  rules:
    - if: "$CI_COMMIT_BRANCH"
      exists:
        - "Chart.yaml"
        - "Chart.lock"
  when: manual

# DefectDojo Engagement Creation:
#   extends:
#     - ".DefectDojo_Engagement_Creation"
