include:
  - local: 'functions.gitlab-ci.yml'

variables:
  DD_UPLOAD_REPORT: "true"

# kube-linter (https://github.com/stackrox/kube-linter)
kube-linter:
  extends:
    - ".sast_base"
    - ".DefectDojo_variables"
  variables:
    IAC_IMAGE: harbor.example.com/devops/kube-linter:latest 
  script:
    - kube-linter lint .
    # - kube-linter lint /path/to/your/yaml.yaml
  rules:
    - if: "$CI_COMMIT_BRANCH"
      exists:
        - "Chart.yaml"
        - "Chart.lock"
  when: manual

# DefectDojo Engagement Creation:
#   extends:
#     - ".DefectDojo_Engagement_Creation"
