include:
  - local: 'functions.gitlab-ci.yml'

variables:
  DD_UPLOAD_REPORT: "true"

# kubesec
kubesec:
  extends:
    - ".sast_base"
  variables:
    IAC_IMAGE: registry.gitlab.com/dc20e6/devsecops/images/kubesec:latest 
    HELM_VALUES_FILES: >
      -f values.yaml
  script:
    - helm template $HELM_VALUES_FILES ./ | kubesec scan /dev/stdin
  when: manual