include:
  - local: 'functions.gitlab-ci.yml'

variables:
  DD_UPLOAD_REPORT: "true"

# Kubescape Scanner (https://github.com/kubescape/kubescape)
Kubescape Helm Scan:
  extends:
    - ".sast_base"
  variables:
    IAC_IMAGE: harbor.example.com/devops/kubescape:v3.0.11
  script:
    - echo $CI_JOB_NAME
    - kubescape scan .
  rules:
    - if: "$CI_COMMIT_BRANCH"
      exists:
        - "Chart.yaml"
        - "Chart.lock"
  when: manual