include:
  - local: 'functions.gitlab-ci.yml'

# Trivy
Trivy K8S Scanning:
  extends:
    - ".sast_base"
  variables:
    IAC_IMAGE: aquasec/trivy:0.51.1
  script:
    - trivy k8s 
      --report summary cluster
