include:
  - local: 'functions.gitlab-ci.yml'

# bearer (https://github.com/Bearer/bearer)
bearer:
  image:
    # name: registry.gitlab.com/dc20e6/devsecops/images/bearer:latest
    name: bearer/bearer
    entrypoint: [""]
  variables:
    SEARCH_MAX_DEPTH: 4
  extends:
    - ".sast_base"
  script:
    - bearer scan
      --format sarif
      --output reports/sast.bearer.report.json
      .
  after_script:
    - echo "Uploading"
    - cat reports/sast.bearer.report.json
  rules:
    - if: "$SAST_EXCLUDED_ANALYZERS =~ /bearer/"
      when: never
    # - if: "$CI_COMMIT_BRANCH && $CI_PROJECT_REPOSITORY_LANGUAGES =~ /(javascript|typescript|ruby|php|go|python|java$|tsx)/"
    - !reference [.sast_rule, rules]
