include:
  - local: 'functions.gitlab-ci.yml'

Forming CycloneDX SBOM (Docker):
  extends:
    - ".audit_image_base"
    - ".audit_rule"
  variables:
    REGISTRY: $CI_REGISTRY
    REGISTRY_USER: $CI_REGISTRY_USER
    REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
    REGISTRY_PATH: $CI_PROJECT_PATH
    TAG: latest
    SYFT_IMAGE: $REGISTRY/$REGISTRY_PATH:$TAG
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/syft:latest
  script:
    - syft login $REGISTRY
      -u $REGISTRY_USER
      -p $REGISTRY_PASSWORD
    - syft scan $SYFT_IMAGE
      -o cyclonedx-json > reports/cdx-sbom.syft.json
  after_script:
    - echo "Uploading"
    - cat reports/cdx-sbom.syft.json
