include:
  - local: 'functions.gitlab-ci.yml'

Forming CycloneDX SBOM (Docker):
  stage: Audit (image)
  extends:
    - ".artifacts"
    - ".audit_base"
    - ".audit_rule"
    - ".DefectDojo_variables"
  variables:
    AUDIT_IMAGE: harbor.example.com/devops/syft:latest
  script:
    - syft login $TARGET_REGISTRY -u $TARGET_REGISTRY_LOGIN -p $TARGET_REGISTRY_PASSWORD
    - syft scan $IMAGE_TO_SCAN
      -o cyclonedx-json > reports/cdx-sbom.syft.json
  after_script:
    - |
      if [ "$DT_UPLOAD_REPORT" = 'true' ]; then
        echo "Uploading"
        dt-wrapper --dt-sbom-path reports/cdx-sbom.syft.json --dt-enable-project-properties
      fi
  when: manual

# Uploading Syft SBOM to Dependency Track:
#   extends:
#     - ".Uploading_SBOM_to_Dependency_Track"
#     - ".audit_rule"
#   variables:
#     SBOM_PATH: $SBOM_PATH_SYFT
#   needs: ["Syft CycloneDX SBOM"]

# DefectDojo Engagement Creation:
#   extends:
#     - ".DefectDojo_Engagement_Creation"
