include:
  - local: 'functions.gitlab-ci.yml'

Forming CycloneDX SBOM (go):
  extends:
    - ".audit_src_base"
    - ".audit_rule"
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/cyclonedx-gomod:1.7.0
  script:
    - /usr/bin/cyclonedx-gomod mod
      -json
      -output reports/cdx-sbom.go.json
      -assert-licenses
      -licenses
      .
  after_script:
    - echo "Uploading"
    - cat reports/cdx-sbom.go.json
  artifacts:
    paths:
      - reports/
    expire_in: 1 day

