include:
  - local: 'functions.gitlab-ci.yml'

Forming CycloneDX SBOM (go):
  extends:
    - ".audit_src_base"
    - ".audit_rule"
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/cyclonedx-gomod:1.7.0
  before_script:
    - mkdir reports/ || true
  script:
    - /usr/bin/cyclonedx-gomod mod
      -json
      -output reports/cdx-sbom.go.json
      -assert-licenses
      -licenses
      .
  after_script:
    - |
      if [ "$DT_UPLOAD_REPORT" = 'true' ]; then
        echo "Uploading"
        cat reports/cdx-sbom.go.json
      fi
  artifacts:
    paths:
      - reports/
    expire_in: 1 day

