include:
  - local: 'functions.gitlab-ci.yml'

Grype SBOM:
  extends:
    - ".audit_src_base"
    - ".audit_rule"
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/grype:latest
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
    # GRYPE_DB_UPDATE_URL: https://grype-db.example.com/listing.json
    GRYPE_DB_CACHE_DIR: /tmp
  script:
    - mkdir /tmp/config || true
    - grype db list
    - grype ./ -o json > reports/audit.grype.report.json
  after_script:
    - echo "Uploading"
    - cat reports/audit.grype.report.json
