Forming CycloneDX SBOM:
  extends:
    - ".audit_src_base"
    - ".audit_rule"
  image:
    name: "maven:3.9.6-eclipse-temurin-17"
  before_script:
    - cp -r settings.xml /usr/share/maven/conf/
  script:
    - mvn install cyclonedx:makeAggregateBom
  after_script:
    - cat target/bom.json
