Forming CycloneDX SBOM (gradle):
  extends:
    - ".audit_src_base"
    - ".audit_rule"
  image:
    name: "gradle:8.7.0-jdk17"
  script:
    - gradle cyclonedxBom
  after_script:
    - mv build/reports/bom.json reports/cdx-sbom.gradle.json
    - |
      if [ "$DT_UPLOAD_REPORT" = 'true' ]; then
        echo "Uploading"
        cat reports/cdx-sbom.gradle.json
      fi
  artifacts:
    paths:
      - build/reports/bom.json
    expire_in: 1 day
