variables:
  SBOM_PATH: "target/bom.json"

stages:
  - Audit (src)

Forming CycloneDX SBOM:
  stage: Audit (src)
  image:
    name: "maven:3.9.6-eclipse-temurin-17"
  before_script:
    - cp -r settings.xml /usr/share/maven/conf/
  script:
    - mvn install cyclonedx:makeAggregateBom
  artifacts:
    paths:
      - target/bom.json
    expire_in: 1 day
