Forming CycloneDX SBOM:
  extends:
    - ".artifacts"
    - ".audit_base"
    - ".audit_rule"
    - ".DefectDojo_variables"
  image:
    name: "maven:3.9.6-eclipse-temurin-17"
  before_script:
    - cp -r settings.xml /usr/share/maven/conf/
  script:
    - mvn install cyclonedx:makeAggregateBom
  artifacts:
    paths:
      - target/bom.json
    expire_in: 1 day
