variables:
  SBOM_PATH: "build/reports/bom.json"

stages:
  - Audit (src)

Forming CycloneDX SBOM:
  stage: Audit (src)
  image:
    name: "gradle:8.7.0-jdk17"
  script:
    - gradle cyclonedxBom
  artifacts:
    paths:
      - build/reports/bom.json
    expire_in: 1 day
