
Forming CycloneDX SBOM (gradle):
  extends:
    - ".artifacts"
    - ".audit_base"
    - ".audit_rule"
    - ".DefectDojo_variables"
  variables:
    AUDIT_IMAGE: "gradle:8.7.0-jdk17"
  script:
    - gradle cyclonedxBom
  artifacts:
    paths:
      - build/reports/bom.json
    expire_in: 1 day
