include:
  - local: 'functions.gitlab-ci.yml'

NPM Audit:
  extends:
    - ".audit_src_base"
    - ".audit_rule"
  image:
    name: "node:18-alpine"
  script:
    - apk add --no-cache git
    - npm audit --json > reports/audit.npm.json
  after_script:
    - echo "Uploading"
    - cat reports/audit.npm.json

Forming CycloneDX SBOM (npm):
  extends:
    - ".audit_src_base"
    - ".audit_rule"
  image:
    name: "node:18-alpine"
  variables:
    SPEC_VERSION: "1.4"                       # (choices: "1.2", "1.3", "1.4", "1.5", "1.6")
    MC_TYPE: "application"                    # (choices: "application", "firmware", "library")
  before_script:
    - npm install --global @cyclonedx/cyclonedx-npm
    - mkdir reports/ || true
  script:
    - cyclonedx-npm
      --spec-version $SPEC_VERSION
      --output-file reports/cdx-sbom.npm.json
      --mc-type $MC_TYPE
  after_script:
    - echo "Uploading"
    - cat reports/cdx-sbom.npm.json

      # --package-lock-only $PACKAGE_LOCK_ONLY

# Forming CycloneDX SBOM (npm) v2:
#   stage: Audit (src)
#   variables:
#     PACKAGE_LOCK_ONLY: "true"
#     SPEC_VERSION: "1.4"                       # (choices: "1.2", "1.3", "1.4", "1.5", "1.6")
#     OUTPUT_FILE: "reports/cdx-sbom.npm.json"
#     MC_TYPE: "application"                    # (choices: "application", "firmware", "library")
#   image:
#     name: "node:18-alpine"
#   before_script:
#     - npx --package @cyclonedx/cyclonedx-npm --call exit
#     - npx @cyclonedx/cyclonedx-npm --help
#     - mkdir reports/ || true
#   script:
#     - npx @cyclonedx/cyclonedx-npm
#       --package-lock-only $PACKAGE_LOCK_ONLY
#       --spec-version $SPEC_VERSION
#       --output-file $OUTPUT_FILE
#       --mc-type $MC_TYPE

# Forming CycloneDX SBOM (npm) v3:
#   stage: Audit (src)
#   variables:
#     PACKAGE_LOCK_ONLY: "true"
#     SBOM_FROMAT: "cyclonedx"
#     SBOM_TYPE: "application"                   # (choices: "application", "firmware", "library")
#     SPEC_VERSION: "1.4"                        # (choices: "1.2", "1.3", "1.4", "1.5", "1.6")
#     OUTPUT_FILE: "reports/cdx-sbom.npm.json"
#   image:
#     name: "node:18-alpine"
#   before_script:
#     - npm install -g npm@latest
#     - npm sbom --help
#     - mkdir reports/ || true
#   script:
#     - npm sbom \
#       --package-lock-only $PACKAGE_LOCK_ONLY \
#       --sbom-format $SBOM_FROMAT \
#       --sbom-type $SBOM_TYPE > $OUTPUT_FILE
