include:
  - local: 'functions.gitlab-ci.yml'

variables:
  SBOM_PATH: "reports/cdx-sbom.php.json"

Forming CycloneDX SBOM:
  extends:
    - ".artifacts"
    - ".audit_base"
    - ".audit_rule"
  variables:
    AUDIT_IMAGE: harbor.example.com/devops/cyclonedx-php:latest
  before_script:
    - mkdir reports/ || true
  script:
    - composer CycloneDX:make-sbom 
      --output-format=JSON
      --output-file=$SBOM_PATH
  after_script:
    - |
      if [ "$DT_UPLOAD_REPORT" = 'true' ]; then
        echo "Uploading"
        dt-wrapper --dt-sbom-path $SBOM_PATH --dt-enable-project-properties
      fi
  when: manual

DefectDojo Engagement Creation:
  extends:
    - ".DefectDojo_Engagement_Creation"
