include:
  - local: 'functions.gitlab-ci.yml'

Forming CycloneDX SBOM (php):
  extends:
    - ".audit_src_base"
    - ".audit_rule"
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/cyclonedx-php:latest
    entrypoint: [""]
  script:
    - composer CycloneDX:make-sbom 
      --output-format=JSON
      --output-file=reports/cdx-sbom.php.json
  after_script:
    - echo "Uploading"
    - cat reports/cdx-sbom.php.json
