include:
  - local: 'functions.gitlab-ci.yml'

variables:
#   PYTHON_DEPENDENCY_MANAGMENT: "environment"   # Build an SBOM from Python (virtual) environment
#   PYTHON_DEPENDENCY_MANAGMENT: "requirements"  # Build an SBOM from Pip requirements
  PYTHON_DEPENDENCY_MANAGMENT: "pipenv"        # Build an SBOM from Pipenv manifest
#   PYTHON_DEPENDENCY_MANAGMENT: "poetry"        # Build an SBOM from Poetry project

Forming CycloneDX SBOM:
  extends:
    - ".artifacts"
    - ".audit_base"
    - ".audit_rule"
  variables:
    AUDIT_IMAGE: harbor.example.com/devops/cyclonedx-py:latest
  script:
    - cyclonedx-py $PYTHON_DEPENDENCY_MANAGMENT
      --output-format json
      --outfile reports/cdx-sbom.py.json
  after_script:
    - |
      if [ "$DT_UPLOAD_REPORT" = 'true' ]; then
        echo "Uploading"
        dt-wrapper --dt-sbom-path $SBOM_PATH --dt-enable-project-properties
      fi
  when: manual

# poetry-audit:
#   extends:
#     - ".audit_base"
#     - ".audit_rule_mr"
#   variables:
#     AUDIT_IMAGE: $CI_REGISTRY/devops/python:3.11.6-p9
#   before_script:
#     - poetry self add ko-poetry-audit-plugin
#   script:
#     - poetry audit --with dev
#   when: manual

# DefectDojo Engagement Creation:
#   extends:
#     - ".DefectDojo_Engagement_Creation"
