stages:
  - Audit (src)

variables:
#   PYTHON_DEPENDENCY_MANAGMENT: "environment"   # Build an SBOM from Python (virtual) environment
#   PYTHON_DEPENDENCY_MANAGMENT: "requirements"  # Build an SBOM from Pip requirements
  PYTHON_DEPENDENCY_MANAGMENT: "pipenv"        # Build an SBOM from Pipenv manifest
#   PYTHON_DEPENDENCY_MANAGMENT: "poetry"        # Build an SBOM from Poetry project

Forming CycloneDX SBOM:
  stage: Audit (src)
  image:
    name: "python:3.12.6-alpine3.20"
  before_script:
    - python -m pip install cyclonedx-bom
    - mkdir reports/ || true
  script:
    - cyclonedx-py $PYTHON_DEPENDENCY_MANAGMENT
      --output-format json
      --outfile reports/cdx-sbom.py.json
  artifacts:
    paths:
      - reports/cdx-sbom.py.json
    expire_in: 1 day
