include:
  - local: 'functions.gitlab-ci.yml'

variables:
  SBOM_PATH: "reports/cdx-sbom.ruby.json"

Forming CycloneDX SBOM (ruby):
  extends:
    - ".audit_src_base"
    - ".audit_rule"
  image:
    name: "ruby:2.7.2"
  script:
    - gem install cyclonedx-ruby
    - cyclonedx-ruby -p . -o $SBOM_PATH
