include:
  - local: 'functions.gitlab-ci.yml'

# ESLint (https://eslint.org/)
eslint (lint):
  extends:
    - ".lint_base"
    - ".lint_rule"
  image:
    name: node:22.9.0-alpine3.20
  variables:
    SEARCH_MAX_DEPTH: 4
  before_script:
    - echo "Здесь необходимо переопределить блок before_script в соответствии с окружением"
  script:
    - echo "Здесь необходимо переопределить блок script в соответствии с окружением"
  when: manual
  allow_failure: true
