include:
  - local: 'functions.gitlab-ci.yml'

# ESLint (https://eslint.org/)
eslint (lint):
  extends:
    - ".lint_base"
    - ".lint_rule"
  image:
    name: node:22.9.0-alpine3.20
  variables:
    SEARCH_MAX_DEPTH: 4
  script:
    - echo "Здесь необходимо переопределить блок script в соответствии с окружением"
  after_script:
    - |
      if [ "$GENERATE_REPORT" = 'true' ]; then
        echo "Uploading"
        cat reports/lint.eslint.yarn.report.json
      fi
  when: manual
  allow_failure: true
