include:
  - local: 'functions.gitlab-ci.yml'

golangci-lint:
  extends:
    - ".lint_base"
    - ".lint_rule"
  variables:
    LINT_IMAGE: harbor.example.com/devops/golangci-lint:latest
  script:
    - golangci-lint run -v
      --issues-exit-code 0
      --print-issued-lines=false
  when: manual
