include:
  - local: 'functions.gitlab-ci.yml'

Dockle Image Scanning:
  stage: SAST (image)
  extends:
    - ".sast_base"
  variables:
    REGISTRY: $CI_REGISTRY
    REGISTRY_USER: $CI_REGISTRY_USER
    REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
    REGISTRY_PATH: $CI_PROJECT_PATH
    TAG: latest
    DOCKLE_IMAGE: $REGISTRY/$REGISTRY_PATH:$TAG
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/dockle:latest
  script:
    - dockle
      --username $REGISTRY_USER
      --password $REGISTRY_PASSWORD
      --insecure
      -f json
      -o reports/iac.dockle.report.json
      $DOCKLE_IMAGE
  after_script:
    - |
      if [ "$GENERATE_REPORT" = 'true' ]; then
        echo "Uploading"
        cat reports/iac.dockle.report.json
      fi
  rules:
    - if: "$SAST_EXCLUDED_ANALYZERS =~ /Dockle Image Scanning/"
      when: never
    - if: "$SAST_DISABLED == 'true' || $SAST_DISABLED == '1'"
      when: never
    - !reference [.security_rule, rules]
