include:
  - local: 'functions.gitlab-ci.yml'

variables:
  DD_UPLOAD_REPORT: "true"

Dockle Image Scanning:
  stage: SAST (image)
  extends:
    - ".sast_base"
    - ".DefectDojo_variables"
  variables:
    SAST_IMAGE: harbor.example.com/devops/dockle:latest
  script:
    - dockle
      --username $HARBOR_LOGIN
      --password $HARBOR_PASSWORD
      --insecure
      -f json
      -o reports/iac.dockle.report.json
      $IMAGE_TO_SCAN
  after_script:
    - |
      if [ "$DD_UPLOAD_REPORT" = 'true' ]; then
        echo "Uploading"
        dd-wrapper --dd-report-file=reports/iac.dockle.report.json --dd-engagement-test-title="Dockle Image Scanning" --dd-engagement-scan-type="Dockle Scan"
      fi
  rules:
    - if: "$SAST_EXCLUDED_ANALYZERS =~ /Dockle Image Scanning/"
      when: never
    - if: "$SAST_DISABLED == 'true' || $SAST_DISABLED == '1'"
      when: never
    - if: $CI_COMMIT_REF_NAME == $SECURITY_BRANCH
  when: manual

DefectDojo Engagement Creation:
  extends:
    - ".DefectDojo_Engagement_Creation"
