include:
  - local: 'functions.gitlab-ci.yml'

Dockle Image Scanning:
  stage: SAST (image)
  extends:
    - ".sast_base"
  variables:
    SAST_IMAGE: registry.gitlab.com/dc20e6/devsecops/images/dockle:latest
  script:
    - dockle
      --username $HARBOR_LOGIN
      --password $HARBOR_PASSWORD
      --insecure
      -f json
      -o reports/iac.dockle.report.json
      $IMAGE_TO_SCAN
  after_script:
    - |
      if [ "$GENERATE_REPORT" = 'true' ]; then
        echo "Uploading"
        cat reports/iac.dockle.report.json
      fi
  rules:
    - if: "$SAST_EXCLUDED_ANALYZERS =~ /Dockle Image Scanning/"
      when: never
    - if: "$SAST_DISABLED == 'true' || $SAST_DISABLED == '1'"
      when: never
    - if: $CI_COMMIT_REF_NAME == $SECURITY_BRANCH
  when: manual