include:
  - local: 'functions.gitlab-ci.yml'

# Anchore Grype (https://github.com/anchore/grype)
Grype Image Scanning:
  stage: SAST (image)
  extends:
    - ".sast_base"
  image:
    name: registry.example.com/openshift/grype:0.74.6-debug
  variables:
    GIT_STRATEGY: none
    DOCKER_CONFIG: "/tmp/config"
    GRYPE_DB_UPDATE_URL: "https://grype-db.example.com/listing.json"
    GRYPE_DB_CACHE_DIR: "/tmp"
  script:
    - mkdir /tmp/config || true
    - grype db list
    - echo "{\"auths\":{\"registry.example.com\":{\"username\":\"serviceaccount\",\"password\":\"$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\"},\"harbor.example.com\":{\"username\":\"$HARBOR_LOGIN\",\"password\":\"$HARBOR_PASSWORD\"}}}" > /tmp/config/config.json
    - grype $IMAGE_TO_SCAN --only-fixed -o json > reports/iac.grype.report.json
  after_script:
    - echo "Uploading"
    - cat reports/iac.grype.report.json
  rules:
    - if: "$SAST_EXCLUDED_ANALYZERS =~ /Grype Image Scanning/"
      when: never
    - if: "$SAST_DISABLED == 'true' || $SAST_DISABLED == '1'"
      when: never
    - if: $CI_COMMIT_REF_NAME == $SECURITY_BRANCH
  when: manual