include:
  - local: 'functions.gitlab-ci.yml'

# Trivy (https://github.com/aquasecurity/trivy)
Trivy Image Scanning:
  stage: SAST (image)
  extends:
    - ".sast_base"
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/trivy:latest
  script:
    - trivy image
      --ignore-unfixed
      --image-config-scanners misconfig,secret
      -o reports/iac.trivy.image.report.json
      --username serviceaccount,"$HARBOR_LOGIN"
      --password "$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)","$HARBOR_PASSWORD"
      $IMAGE_TO_SCAN
  after_script:
    - echo "Uploading"
    - cat reports/iac.trivy.image.report.json
  rules:
    - if: "$SAST_EXCLUDED_ANALYZERS =~ /Trivy Image Scanning/"
      when: never
    - if: "$SAST_DISABLED == 'true' || $SAST_DISABLED == '1'"
      when: never
    - if: $CI_COMMIT_REF_NAME == $SECURITY_BRANCH
  when: manual