include:
  - local: 'functions.gitlab-ci.yml'

variables:
  DD_UPLOAD_REPORT: "true"

# Trivy (https://github.com/aquasecurity/trivy)
Trivy Image Scanning:
  stage: SAST (image)
  extends:
    - ".sast_base"
    - ".DefectDojo_variables"
  variables:
    # SAST_IMAGE: harbor.example.com/devops/trivy:latest
    SAST_IMAGE: registry.example.com/openshift/trivy:0.49.1
  script:
    - trivy image
      --ignore-unfixed
      --image-config-scanners misconfig,secret
      -o reports/iac.trivy.image.report.json
      --username serviceaccount,"$HARBOR_LOGIN"
      --password "$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)","$HARBOR_PASSWORD"
      $IMAGE_TO_SCAN
  after_script:
    - echo "Uploading"
    - dd-wrapper --dd-report-file=reports/iac.trivy.image.report.json --dd-engagement-test-title="Trivy Image Scan" --dd-engagement-scan-type="Trivy Scan"
  rules:
    - if: "$SAST_EXCLUDED_ANALYZERS =~ /Trivy Image Scanning/"
      when: never
    - if: "$SAST_DISABLED == 'true' || $SAST_DISABLED == '1'"
      when: never
    - if: $CI_COMMIT_REF_NAME == $SECURITY_BRANCH
  when: manual

# DefectDojo Engagement Creation:
#   extends:
#     - ".DefectDojo_Engagement_Creation"
