include:
  - local: 'functions.gitlab-ci.yml'

# Trivy (https://github.com/aquasecurity/trivy)
Trivy Image Scanning:
  stage: SAST (image)
  extends:
    - ".sast_base"
  variables:
    REGISTRY: $CI_REGISTRY
    REGISTRY_USER: $CI_REGISTRY_USER
    REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
    REGISTRY_PATH: $CI_PROJECT_PATH
    TAG: latest
    TRIVY_IMAGE: $REGISTRY/$REGISTRY_PATH:$TAG
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/trivy:latest
    entrypoint: [""]
  script:
    - trivy image
      --ignore-unfixed
      --image-config-scanners misconfig,secret
      --format json
      --output reports/iac.trivy.image.report.json
      --username $REGISTRY_USER
      --password $REGISTRY_PASSWORD
      $TRIVY_IMAGE
  after_script:
    - echo "Uploading"
    - cat reports/iac.trivy.image.report.json
  rules:
    - if: "$SAST_EXCLUDED_ANALYZERS =~ /Trivy Image Scanning/"
      when: never
    - if: "$SAST_DISABLED == 'true' || $SAST_DISABLED == '1'"
      when: never
    - !reference [.security_rule, rules]
