include:
  - local: 'functions.gitlab-ci.yml'

mypy:
  extends:
    - ".lint_base"
    - ".lint_rule"
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/mypy:latest
  variables:
    MYPY_SOURCE: .
    MYPY_EXCLUDE: >
      --exclude '/build\.py$'
  script:
    - $PYTHON_INSTALL_CMD
    - mypy
      $MYPY_EXCLUDE
      $MYPY_SOURCE
  when: manual
