include:
  - local: 'functions.gitlab-ci.yml'

mypy:
  extends:
    - ".lint_base"
    - ".lint_rule"
  variables:
    LINT_IMAGE: harbor.example.com/devops/mypy:latest
    MYPY_SOURCE: .
    MYPY_EXCLUDE: >
      --exclude '/build\.py$'
  script:
    - $PYTHON_INSTALL_CMD
    - mypy
      $MYPY_EXCLUDE
      $MYPY_SOURCE
  when: manual
