include:
  - local: 'functions.gitlab-ci.yml'

ruff:
  extends:
    - ".lint_base"
    - ".lint_rule"
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/ruff:latest
  variables:
    RUFF_TARGET_VERSION: py311
    RUFF_SOURCE: .
    RUFF_ARGS: ""
  script:
    - $PYTHON_INSTALL_CMD
    - |
      set -ex
      if [[ -n $RUFF_TARGET_VERSION ]]; then
        RUFF_ARGS="$RUFF_ARGS --target-version $RUFF_TARGET_VERSION"
      fi
      echo "ruff args: $RUFF_ARGS"
      echo "ruff source: $RUFF_SOURCE"
      ruff check $RUFF_ARGS $RUFF_SOURCE
