include:
  - local: 'functions.gitlab-ci.yml'

# Gosec Scanner (https://github.com/securego/gosec)
Gosec:
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/gosec:latest
  variables:
    SEARCH_MAX_DEPTH: 4
  extends:
    - ".sast_base"
  script:
    - ls -la
    - gosec
    - echo gosec > reports/sast.gosec.report.json
  after_script:
    - |
      if [ "$GENERATE_REPORT" = 'true' ]; then
        echo "Uploading"
        cat reports/sast.gosec.report.json
      fi
  rules:
    - if: "$SAST_EXCLUDED_ANALYZERS =~ /gosec/"
      when: never
    - if: "$SAST_DISABLED == 'true' || $SAST_DISABLED == '1'"
      when: never
    # - if: "$CI_COMMIT_BRANCH && $CI_PROJECT_REPOSITORY_LANGUAGES =~ /go/"
    - if: $CI_COMMIT_REF_NAME == $SECURITY_BRANCH
  when: manual
  allow_failure: true