include:
  - local: 'functions.gitlab-ci.yml'

# Helm Lint
Helm Lint:
  extends:
    - ".lint_base"
    - ".lint_rule"
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/helm:latest
  script:
    - helm lint .
