include:
  - local: 'functions.gitlab-ci.yml'

# Helm Lint
Helm Lint:
  extends:
    - ".lint_base"
    - ".lint_rule"
  variables:
    LINT_IMAGE: $CI_REGISTRY/devops/helm:latest
  script:
    - helm lint .
  when: manual
