include:
  - local: 'functions.gitlab-ci.yml'

# Detect-secrets (https://github.com/Yelp/detect-secrets)
Detect-Secrets:
  extends:
    - ".secrets_base"
    - ".secrets_rule"
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/detect-secrets:latest
    entrypoint: [""]
  variables:
    DETECT_SECRETS_IGNORE_FILE: ".detectsecretsingore"
  script:
    - |
      if [ "$DD_UPLOAD_REPORT" = 'true' ]; then
        if [[ -e $DETECT_SECRETS_IGNORE_FILE ]]; then
          detect-secrets scan --word-list $DETECT_SECRETS_IGNORE_FILE . > reports/secrets.detect_secrets.report.json
        else
          detect-secrets scan . > reports/secrets.detect_secrets.report.json
        fi
      else
        if [[ -e $DETECT_SECRETS_IGNORE_FILE ]]; then
          detect-secrets scan --word-list $DETECT_SECRETS_IGNORE_FILE .
        else
          detect-secrets scan .
        fi
      fi
  after_script:
    - |
      if [ "$DD_UPLOAD_REPORT" = 'true' ]; then
        echo "Uploading"
        cat reports/secrets.detect_secrets.report.json
      fi
  when: manual
