include:
  - local: 'functions.gitlab-ci.yml'

# Gitleaks (https://github.com/gitleaks/gitleaks)
GitLeaks:
  extends:
    - ".artifacts"
    - ".secrets_base"
    - ".secrets_rule"
    - ".DefectDojo_variables"
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/gitleaks:latest
    entrypoint: [""]
  script:
    - gitleaks detect
      --source .
      --report-format=json
      --report-path=reports/secrets.gitleaks.report.json
      -v
  # after_script:
  #   - |
  #     if [ "$DD_UPLOAD_REPORT" = 'true' ]; then
  #       echo "Uploading"
  #       dd-wrapper --dd-report-file=reports/secrets.gitleaks.report.json --dd-engagement-test-title="Gitleaks Scan"  --dd-engagement-scan-type="Gitleaks Scan"
  #     fi
  when: manual

# DefectDojo Engagement Creation:
#   extends:
#     - ".DefectDojo_Engagement_Creation"
