include:
  - local: 'functions.gitlab-ci.yml'

# Gitleaks (https://github.com/gitleaks/gitleaks)
GitLeaks:
  extends:
    - ".artifacts"
    - ".secrets_base"
    - ".secrets_rule"
    - ".DefectDojo_variables"
  variables:
    SECRETS_IMAGE: harbor.example.com/devops/gitleaks:latest
  script:
    - gitleaks detect
      --source .
      --report-format=json
      --report-path=reports/secrets.gitleaks.report.json
      -v
  after_script:
    - echo "Uploading"
    - dd-wrapper --dd-report-file=reports/secrets.gitleaks.report.json --dd-engagement-test-title="Gitleaks Scan"  --dd-engagement-scan-type="Gitleaks Scan"
  when: manual

# DefectDojo Engagement Creation:
#   extends:
#     - ".DefectDojo_Engagement_Creation"
