include:
  - local: 'functions.gitlab-ci.yml'

# Gitleaks (https://github.com/gitleaks/gitleaks)
GitLeaks:
  extends:
    - ".secrets_base"
    - ".secrets_rule"
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/gitleaks:latest
    entrypoint: [""]
  script:
    - |
      if [ "$DD_UPLOAD_REPORT" = 'true' ]; then
        gitleaks detect --source . --report-format=json --report-path=reports/secrets.gitleaks.report.json -v
      else
        gitleaks detect --source .
      fi
  after_script:
    - |
      if [ "$DD_UPLOAD_REPORT" = 'true' ]; then
        echo "Uploading"
        cat reports/secrets.gitleaks.report.json
      fi
  when: manual
