include:
  - local: 'functions.gitlab-ci.yml'

# Talisman (https://github.com/thoughtworks/talisman)
Talisman:
  extends:
    - ".artifacts"
    - ".secrets_base"
    - ".secrets_rule"
    - ".DefectDojo_variables"
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/talisman:latest
    entrypoint: [""]
  script:
    - talisman
      --reportDirectory reports/
      --scan
  after_script:
    - mv reports/talisman_reports/data/report.json reports/secrets.talisman.report.json
    - rm -rf reports/talisman_reports/
    - |
      if [ "$DD_UPLOAD_REPORT" = 'true' ]; then
        echo "Uploading"
        cat reports/secrets.talisman.report.json
      fi
  #       dd-wrapper --dd-report-file=reports/secrets.talisman.report.json --dd-engagement-test-title="Talisman Scan"  --dd-engagement-scan-type="Talisman Scan"
  when: manual

# DefectDojo Engagement Creation:
#   extends:
#     - ".DefectDojo_Engagement_Creation"
