include:
  - local: 'functions.gitlab-ci.yml'

# Trufflehog3 (https://github.com/feeltheajf/trufflehog3)
Trufflehog3:
  extends:
    - ".artifacts"
    - ".secrets_base"
    - ".secrets_rule"
    - ".DefectDojo_variables"
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/trufflehog3:latest
    entrypoint: [""]
  script:
    - |
      if [ "$DD_UPLOAD_REPORT" = 'true' ]; then
        trufflehog3 -f JSON -o reports/secrets.trufflehog3.report.json .
      else
        trufflehog3 .
      fi
  after_script:
    - |
      if [ "$DD_UPLOAD_REPORT" = 'true' ]; then
        echo "Uploading"
        dd-wrapper --dd-report-file=reports/secrets.trufflehog3.report.json --dd-engagement-test-title="Trufflehog3 Scan" --dd-engagement-scan-type="Trufflehog3 Scan"
      fi
  when: manual

# DefectDojo Engagement Creation:
#   extends:
#     - ".DefectDojo_Engagement_Creation"
