include:
  - local: 'functions.gitlab-ci.yml'

# Trufflehog3 (https://github.com/feeltheajf/trufflehog3)
Trufflehog3:
  extends:
    - ".secrets_base"
    - ".secrets_rule"
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/trufflehog3:latest
    entrypoint: [""]
  script:
    - |
      if [ "$GENERATE_REPORT" = 'true' ]; then
        trufflehog3 -f JSON -o reports/secrets.trufflehog3.report.json .
      else
        trufflehog3 .
      fi
  after_script:
    - |
      if [ "$GENERATE_REPORT" = 'true' ]; then
        echo "Uploading"
        cat reports/secrets.trufflehog3.report.json
      fi
  when: manual
