include:
  - local: 'functions.gitlab-ci.yml'

php-lint:
  extends:
    - ".lint_base"
    - ".lint_rule"
  variables:
    LINT_IMAGE: registry.gitlab.com/dc20e6/devsecops/images/phplint:latest
  script:
    - lint .
  when: manual
