include:
  - local: 'functions.gitlab-ci.yml'

phplint:
  extends:
    - ".lint_base"
    - ".lint_rule"
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/phplint:latest
    entrypoint: [""]
  script:
    - phplint .
