include:
  - local: 'functions.gitlab-ci.yml'

# KICS Scanner (https://github.com/Checkmarx/kics)
KICS Scanning:
  extends:
    - ".sast_base"
    - ".DefectDojo_variables"
    - ".default_runner_resource_request"
  variables:
    IAC_IMAGE: harbor.example.com/devops/kics:latest
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: "builder"
  script:
    - kics scan
      --no-progress
      --output-path reports/
      --output-name lint.kics_k8s.report.json
      --report-formats json
      --path .
      --ignore-on-exit all
  rules:
    - if: "$CI_COMMIT_BRANCH"
      exists:
        - "Chart.yaml"
        - "Chart.lock"
  when: manual

# Kubescape Scanner (https://github.com/kubescape/kubescape)
Kubescape Helm Scan:
  extends:
    - ".sast_base"
    - ".DefectDojo_variables"
    - ".default_runner_resource_request"
  variables:
    IAC_IMAGE: harbor.example.com/devops/kubescape:v3.0.11
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: "builder"
  script:
    - echo $CI_JOB_NAME
    - kubescape scan .
  rules:
    - if: "$CI_COMMIT_BRANCH"
      exists:
        - "Chart.yaml"
        - "Chart.lock"
  when: manual

# Trivy
Trivy K8S Scanning:
  extends:
    - ".sast_base"
    - ".DefectDojo_variables"
    - ".extended_runner_resource_request"
  variables:
    IAC_IMAGE: aquasec/trivy:0.51.1
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: "builder"
  script:
    - trivy k8s 
      --report summary cluster
  when: manual

# chart-testing
chart-testing:
  extends:
    - ".sast_base"
    - ".DefectDojo_variables"
    - ".extended_runner_resource_request"
  variables:
    IAC_IMAGE: quay.io/helmpack/chart-testing:v3.11.0
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: "builder"
  script:
    - ct install
      --chart-dirs . 
      --charts .
  rules:
    - if: "$CI_COMMIT_BRANCH"
      exists:
        - "Chart.yaml"
        - "Chart.lock"
  when: manual

# chechov (https://github.com/bridgecrewio/checkov)
checkov:
  extends:
    - ".sast_base"
    - ".DefectDojo_variables"
    - ".extended_runner_resource_request"
  variables:
    IAC_IMAGE: $CI_REGISTRY/devops/checkov:3.2.91
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: "builder"
  script:
    - checkov
      --framework helm
      -d .
      -o cli
      # -o json
      # --output-file-path reports/
  rules:
    - if: "$CI_COMMIT_BRANCH"
      exists:
        - "Chart.yaml"
        - "Chart.lock"
  when: manual

# kube-linter (https://github.com/stackrox/kube-linter)
kube-linter:
  extends:
    - ".sast_base"
    - ".DefectDojo_variables"
    - ".extended_runner_resource_request"
  variables:
    IAC_IMAGE: harbor.example.com/devops/kube-linter:latest 
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: "builder"
  script:
    - kube-linter lint .
    # - kube-linter lint /path/to/your/yaml.yaml
  rules:
    - if: "$CI_COMMIT_BRANCH"
      exists:
        - "Chart.yaml"
        - "Chart.lock"
  when: manual

# kube-score (https://github.com/zegl/kube-score)
kube-score:
  extends:
    - ".sast_base"
    - ".DefectDojo_variables"
    - ".extended_runner_resource_request"
  variables:
    IAC_IMAGE: zegl/kube-score:v1.18.0
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: "builder"
    HELM_VALUES_FILES: >
      -f values.yaml
  script:
    - helm template $HELM_VALUES_FILES . | kube-score score -
      --output-format sarif
  rules:
    - if: "$CI_COMMIT_BRANCH"
      exists:
        - "Chart.yaml"
        - "Chart.lock"
  when: manual

# kubeconform (https://github.com/yannh/kubeconform)
kubeconform:
  extends:
    - ".sast_base"
    - ".DefectDojo_variables"
    - ".extended_runner_resource_request"
  variables:
    IAC_IMAGE: $CI_REGISTRY/devops/deploy-tools:latest
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: "builder"
    HELM_VALUES_FILES: >
      -f values.yaml
  script:
    - helm plugin install https://github.com/jtyr/kubeconform-helm
    - helm kubeconform
      --verbose
      --summary
      $HELM_VALUES_FILES
      .
  when: manual

# kubesec
kubesec:
  extends:
    - ".sast_base"
    - ".DefectDojo_variables"
    - ".extended_runner_resource_request"
  variables:
    IAC_IMAGE: harbor.example.com/devops/kubesec:latest 
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: "builder"
    HELM_VALUES_FILES: >
      -f values.yaml
  script:
    - helm template $HELM_VALUES_FILES ./ | kubesec scan /dev/stdin
  when: manual

# Kube-bench

#
# DefectDojo Engagement Creation:
#   extends:
#     - ".DefectDojo_Engagement_Creation"
