include:
  - local: 'functions.gitlab-ci.yml'

# kubesec
kubesec:
  extends:
    - ".sast_base"
    - ".DefectDojo_variables"
  variables:
    IAC_IMAGE: harbor.example.com/devops/kubesec:latest 
    HELM_VALUES_FILES: >
      -f values.yaml
  script:
    - helm template $HELM_VALUES_FILES ./ | kubesec scan /dev/stdin
  when: manual

DefectDojo Engagement Creation:
  extends:
    - ".DefectDojo_Engagement_Creation"
