include:
  - local: 'functions.gitlab-ci.yml'

# progpilot (https://github.com/designsecurity/progpilot)
progpilot:
  variables:
    SAST_IMAGE: harbor.example.com/devops/progpilot:latest
    SEARCH_MAX_DEPTH: 4
  extends:
    - ".sast_base"
    - ".DefectDojo_variables"
  script:
    - echo progpilot
    - echo progpilot > reports/sast.progpilot.report.json
  after_script:
    - |
      if [ "$DD_UPLOAD_REPORT" = 'true' ]; then
        echo "Uploading"
        dd-wrapper --dd-report-file=reports/sast.progpilot.report.json --dd-engagement-test-title="Progpilot Scan" --dd-engagement-scan-type="Progpilot Scan"
      fi
  rules:
    - if: "$SAST_EXCLUDED_ANALYZERS =~ /progpilot/"
      when: never
    - if: "$SAST_DISABLED == 'true' || $SAST_DISABLED == '1'"
      when: never
    # - if: "$CI_COMMIT_BRANCH && $CI_PROJECT_REPOSITORY_LANGUAGES =~ /php/"
    - if: $CI_COMMIT_REF_NAME == $SECURITY_BRANCH
  when: manual
  allow_failure: true

DefectDojo Engagement Creation:
  extends:
    - ".DefectDojo_Engagement_Creation"
