include:
  - local: 'functions.gitlab-ci.yml'

# PMD (https://github.com/pmd/pmd)
pmd:
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/pmd:latest
  variables:
    SEARCH_MAX_DEPTH: 4
    PMD_LANGUAGE: java
    PMD_LANGUAGE_RULESETS: rulesets
    PMD_MINIMUM_TOKENS: 0
  extends:
    - ".sast_base"
  script:
    - /pmd-bin-7.1.0/bin/pmd check 
      -d .
      -f json
      -r reports/sast.pmd.report.json
  rules:
    - if: "$SAST_EXCLUDED_ANALYZERS =~ /pmd/"
      when: never
    - if: "$SAST_DISABLED == 'true' || $SAST_DISABLED == '1'"
      when: never
    # - if: "$CI_COMMIT_BRANCH && $CI_PROJECT_REPOSITORY_LANGUAGES =~ /java$/"
    - if: $CI_COMMIT_REF_NAME == $SECURITY_BRANCH
  when: manual
  allow_failure: true