include:
  - local: 'functions.gitlab-ci.yml'

golangci-lint:
  extends:
    - ".lint_base"
    - ".lint_rule"
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/golangci-lint:latest
  script:
    - golangci-lint run -v
      --issues-exit-code 0
      --print-issued-lines=false
  when: manual
