include:
  - local: 'functions.gitlab-ci.yml'

# Burp Dastardly
Dastardly:
  extends:
    - ".dast_base"
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/dastardly:2024.4.1
    entrypoint: [dastardly-entrypoint.sh]
  variables:
    BURP_START_URL: https://$DAST_WEBSITE
    BURP_REPORT_FILE_PATH: reports/dast.dastardly.report.xml
  script:
    - /usr/local/burpsuite_enterprise/bin/dastardly
  after_script:
    - echo "Uploading"
    - cat reports/dast.dastardly.report.xml
  rules:
    - if: $DAST_WEBSITE

DefectDojo Engagement Creation:
  extends:
    - ".DefectDojo_Engagement_Creation"
