include:
  - local: 'functions.gitlab-ci.yml'

# Nikto (https://github.com/sullo/nikto)
nikto:
  extends:
    - ".dast_base"
  variables:
    DAST_IMAGE: harbor.example.com/devops/nikto:latest
  script:
    - echo $CI_JOB_NAME
    - nikto.pl
      -host $DAST_WEBSITE
      -o reports/dast.nikto.report.json
  after_script:
    - echo "Uploading"
    - cat reports/dast.nikto.report.json
  rules:
    - if: $DAST_WEBSITE
  when: manual

Nikto (all):
  extends:
    - ".dast_base"
  variables:
    DAST_IMAGE: harbor.example.com/devops/nikto:latest
  script:
    - echo $CI_JOB_NAME
    - nikto.pl
      -host $DAST_WEBSITE
      -o reports/dast.nikto_all.report.json
      -C all
  after_script:
    - echo "Uploading"
    - cat reports/dast.nikto_all.report.json
  rules:
    - if: $DAST_WEBSITE
  when: manual

DefectDojo Engagement Creation:
  extends:
    - ".DefectDojo_Engagement_Creation"
