include:
  - local: 'functions.gitlab-ci.yml'

# Nuclei (https://github.com/projectdiscovery/nuclei)
Nuclei:
  extends:
    - ".dast_base"
  variables:
    DAST_IMAGE: harbor.example.com/devops/nuclei:latest
  script:
    - echo $CI_JOB_NAME
    - nuclei
      -target $DAST_WEBSITE
      -json-export reports/dast.nuclei.report.json
  after_script:
    - echo "Uploading"
    - dd-wrapper --dd-report-file=reports/dast.nuclei.report.json --dd-engagement-test-title="Nuclei" --dd-engagement-scan-type="Nuclei Scan"
  rules:
    - if: $DAST_WEBSITE
  when: manual

DefectDojo Engagement Creation:
  extends:
    - ".DefectDojo_Engagement_Creation"
