include:
  - local: 'functions.gitlab-ci.yml'

# Nuclei (https://github.com/projectdiscovery/nuclei)
Nuclei:
  extends:
    - ".dast_base"
  variables:
    DAST_IMAGE: registry.gitlab.com/dc20e6/devsecops/images/nuclei:latest
  script:
    - echo $CI_JOB_NAME
    - nuclei
      -target $DAST_WEBSITE
      -json-export reports/dast.nuclei.report.json
  after_script:
    - echo "Uploading"
    - cat reports/dast.nuclei.report.json
  rules:
    - if: $DAST_WEBSITE
  when: manual

DefectDojo Engagement Creation:
  extends:
    - ".DefectDojo_Engagement_Creation"
