include:
  - local: 'functions.gitlab-ci.yml'

# Wapiti Scan (https://github.com/inc775/wapiti-3.0.0)
Wapiti:
  extends:
    - ".dast_base"
  variables:
    DAST_IMAGE: registry.gitlab.com/dc20e6/devsecops/images/wapiti:3.1.8
  script:
    - wapiti
      --url http://$DAST_WEBSITE
      --format xml
      --output ./reports/dast.wapiti.report.xml
  after_script:
    # - sed -i '/info name="auth"/d' ./reports/dast.wapiti.report.xml
    - echo "Uploading"
    - cat reports/dast.wapiti.report.xml
  rules:
    - if: $DAST_WEBSITE
  when: manual
  allow_failure: true

DefectDojo Engagement Creation:
  extends:
    - ".DefectDojo_Engagement_Creation"
