include:
  - local: 'functions.gitlab-ci.yml'

# ESLint (https://eslint.org/)
eslint (lint):
  extends:
    - ".lint_base"
    - ".lint_rule"
  variables:
    LINT_IMAGE: harbor.example.com/devops/node:18.20.3-p10
    SEARCH_MAX_DEPTH: 4
  script:
    - echo "Здесь необходимо переопределить блок script в соответствии с окружением"
  after_script:
    - |
      if [ "$DD_UPLOAD_REPORT" = 'true' ]; then
        echo "Uploading"
        cat reports/lint.eslint.report.json
      fi
  when: manual
  allow_failure: true
