include:
  - local: 'functions.gitlab-ci.yml'

variables:
  DD_UPLOAD_REPORT: "true"

".mobsf":
  variables:
    SAST_IMAGE: $CI_REGISTRY/devops/python:3.11.6-p9
    SEARCH_MAX_DEPTH: 4
  extends:
    - ".sast_base"
  rules:
    - when: never
  script:
    - echo mobsf
  allow_failure: true

# +
mobsf-android:
  variables:
    SAST_IMAGE: $CI_REGISTRY/devops/python:3.11.6-p9
    SEARCH_MAX_DEPTH: 4
  extends:
    - ".mobsf"
  script:
    - echo mobsf-android
    - echo mobsf-android > reports/sast.mobsf-android.report.json
  rules:
    - if: "$SAST_DISABLED == 'true' || $SAST_DISABLED == '1'"
      when: never
    - if: "$SAST_EXCLUDED_ANALYZERS =~ /mobsf/"
      when: never
    - if: "$CI_COMMIT_BRANCH && $SAST_EXPERIMENTAL_FEATURES == 'true'"
      exists:
        - "**/*.apk"
        - "**/AndroidManifest.xml"
  allow_failure: true
  when: manual