include:
  - local: 'functions.gitlab-ci.yml'

variables:
  CI_DOCKERFILE: Dockerfile

# KICS Scanner (https://github.com/Checkmarx/kics)
KICS Dockerfile Scanning:
  extends:
    - ".lint_base"
    - ".lint_rule"
  image:
    name: registry.gitlab.com/dc20e6/devsecops/images/kics:latest
  script:
    - kics scan
      --no-progress
      --output-path reports/
      --output-name lint.kics_dockerfile.report.json
      --report-formats json
      --path ${CI_DOCKERFILE}
      --ignore-on-exit all
  after_script:
    - echo "Uploading"
    - cat reports/lint.kics_dockerfile.report.json
