include:
  - local: 'functions.gitlab-ci.yml'

# Kubescape Scanner (https://github.com/kubescape/kubescape)
Kubescape Cluster Scan:
  extends:
    - ".dast_base"
  variables:
    IAC_IMAGE: registry.gitlab.com/dc20e6/devsecops/images/kubescape:v3.0.11
  script:
    - echo $CI_JOB_NAME
    - kubescape scan --kubeconfig cluster.conf
  rules:
    - if: "$CLUSTER_SCAN == 'true' || $CLUSTER_SCAN == '1'"

DefectDojo Engagement Creation:
  extends:
    - ".DefectDojo_Engagement_Creation"
