include:
  - local: 'functions.gitlab-ci.yml'

# Popeye (https://github.com/derailed/popeye)
popeye:
  extends:
    - ".dast_base"
  variables:
    IAC_IMAGE: registry.gitlab.com/dc20e6/devsecops/images/popeye:v0.21.3
  script:
    - echo $CI_JOB_NAME
    - popeye
  rules:
    - if: "$CLUSTER_SCAN == 'true' || $CLUSTER_SCAN == '1'"

DefectDojo Engagement Creation:
  extends:
    - ".DefectDojo_Engagement_Creation"
