include:
  - local: 'functions.gitlab-ci.yml'

# prowler (https://github.com/prowler-cloud/prowler)
prowler:
  extends:
    - ".dast_base"
  variables:
    IAC_IMAGE: harbor.example.com/devops/prowler:latest
  script:
    - prowler kubernetes --help
  rules:
    - if: "$CLUSTER_SCAN == 'true' || $CLUSTER_SCAN == '1'"
  when: manual

DefectDojo Engagement Creation:
  extends:
    - ".DefectDojo_Engagement_Creation"
